name: MarKor Network ESP Programmer
version: "0.0.1"

slug: network_esp_programmer
description: Programowanie urządzeń ESP8266 i ESP32 przez sieć (RFC2217)

url: https://github.com/markor150/MarKor-Network-ESP-Programmer

arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto
init: false

ingress: true
ingress_port: 8099

panel_icon: mdi:chip
panel_title: ESP Programmer

ports:
  8099/tcp: 8099

ports_description:
  8099/tcp: Web interface

map: []

options:
  programmers: []

schema:
  programmers:
    - name: str
      host: str
      port: int
