build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.22
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  armv7: ghcr.io/home-assistant/armv7-base:3.22
labels:
  org.opencontainers.image.title: "MarKor Network ESP Programmer"
  org.opencontainers.image.description: "Home Assistant Add-on do programowania ESP przez RFC2217"
  org.opencontainers.image.source: "https://github.com/markor150/MarKor-Network-ESP-Programmer"
